feature_extract_enable : 0
point_filter_num : 1
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.1
filter_size_map : 0.4
cube_side_length : 20
grid_size : 40
patch_size : 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 500 # 1000
laser_point_cov : 0.001 # 0.001
pose_output_en: false
delta_time: 0.1

common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"

preprocess:
    lidar_type: 1 # 1:Livox LiDAR  2:VELO16  3:OUST64  4:XT32  5:Mid360
    scan_line: 6 # 16  64  32
    blind: 1 # blind x m disable

mapping:
    acc_cov_scale: 10
    gyr_cov_scale: 100
    extrinsic_T: [ 0.04165, 0.02326, -0.0284 ] # horizon 0.05512, 0.02226, -0.0297
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

pcd_save:
    pcd_save_en: false

camera:
    img_topic: /hk_camera/image_color
    # E2
    # Rcl: [0.0288810,-0.9994270,-0.0176385,
    #       -0.0117679,0.0173046,-0.9997810,
    #       0.9995140,0.0290823,-0.0112614]
    # Pcl: [-0.00429101,-0.0194753,-0.00845176]


    # 20241107 
    # direct_visual_lidar_calibrate 
    # Roll : 178.945 , Pitch : -179.824 , Yaw : 179.958
    Rcl: [  0.00361801 ,  -0.999867 , -0.0159037 , 
           -0.00788998 ,  0.0158748 ,  -0.999843 ,
            0.999962 , 0.00374293 , -0.0078315 ]
    Pcl: [ -0.0148726, 0.074121, -0.0760439 ]